name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.0.1=py37_0
  - blas=1.0=openblas
  - ca-certificates=2019.10.16=0
  - cartopy=0.17.0=py37hd759880_1006
  - certifi=2019.9.11=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - conda=4.7.12=py37_0
  - conda-package-handling=1.6.0=py37h7b6447c_0
  - cryptography=2.7=py37h1ba5d50_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - expat=2.2.5=he1b5a44_1004
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_1
  - geos=3.7.2=he1b5a44_2
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py37_0
  - imageio=2.6.1=py37_0
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py37hc9558a2_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h6e990d7_2
  - libpng=1.6.37=hed695b0_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=hfc65ed5_1004
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hea5a465_1
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.1.1=py37h5429711_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.17.2=py37hf9bf1b6_0
  - numpy-base=1.17.2=py37h2f8d375_0
  - olefile=0.46=py_0
  - openssl=1.1.1d=h7b6447c_3
  - owslib=0.18.0=py_0
  - pandas=0.25.2=py37he6710b0_0
  - pcre=8.43=he1b5a44_0
  - pillow=6.2.0=py37h34e0f95_0
  - pip=19.2.3=py37_0
  - proj4=5.2.0=he1b5a44_1006
  - pthread-stubs=0.4=h14c3975_1001
  - pycosat=0.6.3=py37h14c3975_0
  - pycparser=2.19=py37_0
  - pyepsg=0.4.0=py_0
  - pykdtree=1.3.1=py37h3010b51_1002
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyproj=1.9.6=py37h14380d9_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py_0
  - pytz=2019.3=py_0
  - qt=5.9.7=h52cfd70_2
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_0
  - ruamel_yaml=0.15.46=py37h14c3975_0
  - scipy=1.3.1=py37h921218d_2
  - setuptools=41.4.0=py37_0
  - shapely=1.6.4=py37hec07ddf_1006
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.30.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.36.1=py_0
  - urllib3=1.24.2=py37_0
  - wheel=0.33.6=py37_0
  - xarray=0.13.0=py_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.3=h3b9ef0a_0
  - pip:
    - cftime==1.0.4.2
    - cfunits==3.2.4
    - h5py==2.10.0
    - imageio-ffmpeg==0.3.0
    - netcdf4==1.5.3
prefix: /opt/conda

